/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "task.h"
#include "scheduler.h"
#include "led_controller.h"
//#define OPENOCD_SEMIHOSTING_ENABLED
#ifdef OPENOCD_SEMIHOSTING_ENABLED
extern void initialise_monitor_handles(void);
#endif /* OPENOCD_SEMIHOSTING_ENABLED */

int main(void)
{
#ifdef OPENOCD_SEMIHOSTING_ENABLED
	initialise_monitor_handles();
	printf("Semihosting works\n");
#endif /* OPENOCD_SEMIHOSTING_ENABLED */

	init_leds();
	init_and_run_scheduler();

    /* Should never come here. In case of all tasks are finished/blocked, "task_idle" will run.  */
}
